services:
    newsapi_webserver:
        image: nginx:alpine
        container_name: "newsapi_webserver"
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    newsapi_php:
        build:
            context: .
            dockerfile: "docker/php/Dockerfile"
        container_name: "newsapi_php"
        volumes:
            - .:/application
        networks:
            - newsapi_net
    newsapi_node:
        build:
            context: .
            dockerfile: "docker/node/Dockerfile"
        container_name: "newsapi_node"
        volumes:
            - .:/application
        networks:
            - newsapi_net
    newsapi_db:
        image: mysql:8
        container_name: "newsapi_db"
        ports:
            - "3313:3306"
        environment:
            MYSQL_DATABASE: "newsapi"
            MYSQL_USER: "newsapi"
            MYSQL_PASSWORD: "newsapi"
            MYSQL_ROOT_PASSWORD: "newsapi"
        volumes:
            - ../db/newsapi:/var/lib/mysql
        networks:
            - newsapi_net
networks:
    newsapi_net:
        driver: bridge
